project:
  type: website
  output-dir: _site

website:
  title: "Ai4MatLectures"
  navbar:
    left:
      - href: index.qmd
        text: Home

execute:
  freeze: auto

format:
  html:
    css: styles.css
    fontsize: 14pt
    theme:
      - darkly
      - custom.scss
    toc: true
    code-fold: false
