project:
  type: website
  output-dir: _site

website:
  title: "Ai4MatLectures"
  navbar:
    left:
      - href: index.qmd
        text: Home

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    toc: true
    code-fold: false
